---
title: "Registered Reports in Linguistics: Quarto template"
format:
  rrling-pdf: default
  rrling-html: default
author:
  - name: Stefano Coretta
    orcid: 0000-0001-9627-5532
    affiliations:
      - ref: UOE
  - name: Jessica Hampton
    orcid: 0000-0001-6871-2846
    affiliations:
      - ref: UOL
# Specify the short authors list which is printed in the header
shortauthors: "Hampton Coretta"
affiliations:
  - id: UOE
    name: University of Edinburgh
  - id: UOL
    name: University of of Liverpool
abstract: |
  This abstract serves as a generic template to guide authors in crafting effective summaries of their academic work. An ideal abstract should succinctly present the purpose of the study, the methodology employed, the key findings, and the principal conclusions. Begin by clearly stating the research question or objective, ensuring it reflects the core focus of the article. Follow with a brief description of the methods used, highlighting the design, data sources, and analytical techniques where applicable. Then, summarize the most significant results, avoiding excessive detail or technical jargon. Conclude with a statement on the broader implications or potential applications of the findings. The abstract should be self-contained, written in the past tense (except for conclusions or implications, which may be in the present), and limited to 200–250 words. Avoid citations, abbreviations, or references to tables and figures. Emphasize clarity, precision, and coherence to ensure accessibility to a wide readership, including those outside the immediate disciplinary field.

# Please, set your keywords here
keywords: [template, demo]

# Indicate the DOI of your Research Compendium
rescompendium: "https://www.doi.org/10.1000/182"

# Use the stageone field to specify the link (url or doi) to the PCI RR recommendation of
# the Stage 1 manuscript once the manuscript is recommended.
stageone: ""

# Use the stagetwo field to specify the link (url or doi) to the PCI RR recommendation of
# the Stage 2 manuscript once the manuscript is recommended.
stagetwo: ""

# List your bib files here
bibliography: bibliography.bib
# Use the Unified stylesheet (please don't change this)
csl: unified.csl

# If your article includes different scripts, you can specify them here.
# See the "Typefaces" section below. To test this template you need the Yuppy SC and 
# Note Seriv Devanagari fonts, which are available on Google Fonts.
uchar:
  groups:
    - group: CJK
      font: Yuppy SC
    - group: Devanagari
      font: Noto Serif Devanagari
---

## The RRLing templates {.unnumbered}

All submissions to Registered Reports in Linguistics (RRLing) must use this Quarto template (<https://github.com/stefanocoretta/rrling>) or the companion LaTeX template (<https://www.overleaf.com/read/bbcpjgrnvpny#8ae823>). We strongly encourage authors to use the Quarto template (especially if their study involves any type of statistical analysis). If you are new to both LaTeX and Quarto, then we suggest to use Quarto with RStudio/Positron for a smoother writing experience if your study has computational code (so that you can embed the code in the manuscript), or to use LaTeX on Overleaf if you don't need support for computational code in the manuscript.

**Both Quarto and LaTeX documents can be rendered to PDF and this will be the final format used for accepted papers. Note that we will not accept papers that are not written with one of the templates.** This is because we don't have resources for typesetting accepted articles and by using the official templates, no further special typesetting is needed.

### LaTeX {.unnumbered}

If you are new to LaTeX, you can learn the basics here: <https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes>. The LaTeX template can be found at <https://www.overleaf.com/read/bbcpjgrnvpny#8ae823> and used online on Overleaf (<https://www.overleaf.com>) or can be downloaded to your computer. The template is designed to showcase the basic structure of an article submitted to RRLing, including examples of specific typesetting requirements.

### Quarto {.unnumbered}

Quarto (<https://quarto.org>) is a new publishing system that allows you to write text and code in a single document. The document can be rendered to a variety of formats, including the PDF format required for submission to RRLing.

A Quarto document can dynamically include in the rendered document the output of computational code, such as summary tables and plots, with the advantage that, if the code changes, the new output is automatically reflected in the document when rendered. An introduction to using Quarto can be found here: <https://quarto.org/docs/get-started/>. This Quarto template is available here: <https://github.com/stefanocoretta/rrling>.

The Quarto template for submissions to RRLing can be found at <https://github.com/stefanocoretta/rrling>. We recommend using RStudio/Positron to write with the Quarto template, but any other workflow you already use will do.

## Article structure {#article-structure .unnumbered}

All articles submitted to RRLing should have the following structure:

1.  Introduction

2.  Methods

3.  Results

4.  Discussion

5.  Conclusion

6.  (unnumbered) CRediT roles

7.  (unnumbered) Acknowledgements (optional)

8.  (unnumbered) Open Research statement

9.  (unnumbered) Conflict of interest

10. (unnumbered) References

Note that in the Stage 1 manuscript, only the following sections are
necessary: Introduction, Methods, CRediT roles, Open Research statement,
Conflict of interest. You will not be able to make changes to the
Introduction and Methods section in the Stage 2 manuscript (barring
minor typographical or grammatical edits).

You should also provide an abstract (250 words max), keywords and a link
to the Research Compendium of the study (this can be a URL or a DOI).
The Research Compendium is an online repository containing all the
materials of the study, including but not limited to, all stimuli, data,
code, figures, and so on.

The following sections mirror the sections that articles submitted to
RRLing should have. Each section provides information on what the
section should include. Within each section, it is up to the author to
include subsections (no specific requirements are in place in this case,
but we encourage authors to make use of subsections to aid readers).

## Introduction

The Introduction should include a general overview of the research
topic, followed by a review of existing relevant literature to summarise
existing knowledge. It is not expected that authors include all the
existing literature, under the assumption that due diligence was carried
out. We rather encourage authors to point readers to existing literature
reviews, if they exist and are relevant. Suggested subsections include a
"Background" or "Literature Review" subsection and a "Research
Questions/Hypotheses" subsection.

### Typography {#typography .unnumbered}

#### Typefaces {.unnumbered}

You can mix scripts thanks to the LaTeX package `ucharclasses`. For
example, this is Chinese 普通話 *pǔtōnghuà* and this is Sankrit देवनागरी
*devanāgarī*. The Latin font is Source Sans Pro and should not be
changed. Source Sans Pro also includes graphs from the International
Phonetic Alphabet: \[ˌɪntəˈnæʃənəl fəˈnɛtɪk ˈælfəbɛt\].

#### Tables and figures {.unnumbered}

You can include tables like @tbl-letters. The caption will be placed above the table. You can
also include figures, like @fig-example. Place the caption below the figure. Note that
table and figure positioning is managed by LaTeX: do not force placement
with LaTeXplacement options. You can use sub-figures and a two-column
layout if it uses the space better.

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption {#tbl-letters}

![The Registered Reports in Linguistics
logo.](rrling-logo-bg.png){#fig-example width="25%"}

#### Linguistic examples and interlinear glosses {.unnumbered}

If you need to include linguistic examples or interlinear glosses, please use the interlinear Quarto extension: <https://github.com/stefanocoretta/interlinear>. If the extension is too limited for your glossing needs, we recommend to use the LaTeX template instead so that you can exploit the full capabilities of the LaTeX package expex.

#### Bibliography {.unnumbered}

The `bibliography.bib` file has a few example entries in BiBTeX format. To cite use the [Quarto citation syntax](https://quarto.org/docs/authoring/citations.html): for example @alfarano2021. You can also include both author and year within the parentheses [@croft2002]. You can specify pages and custom text [see @jakobson1951, pp. 47-52; and @lindsey2017].

Bibliographical entries will be added to the (unnumbered) ``References`` section at the end of the article.

## Methods

The Methods section should provide detailed information about the
methods that will be employed in the study after In Principle Acceptance
of the Stage 1 Registered Report manuscript. There should be enough
details for reviewers to be able to reproduce exactly the same pipeline
employed in the study (at Stage 1) and for reviewers and independent
researchers to obtain the same results which will be reported on the
Stage 2 manuscript. This level of detail will also make replication
attempts more straightforward.

Note that, according to principles of Open Research which are mandated
for submission to this Journal, you must ensure that all materials
belonging to the Methods section at Stage 1 are available, including
e.g. task-related files, programming code, questionnaires, interview
prompts, deductive models for thematic analysis, pre-existing corpora
etc.

## Results

After your Stage 1 manuscript has been In Principle Accepted and you
have conducted your study, this section in the Stage 2 manuscript should
report the results of the methods described in the previous session. The
outcome of all registered analysis from the Stage 1 manuscript must be
reported in this section. Further, non-registered analyses, can be
included under a separate subsection and clearly flagged as
non-registered (for example in a subsection called "Non-registered
analyses").

As stated above, Open Research principle are mandated for submission to
this Journal, so all materials that have been output by the methods
described in the previous section must be openly available. \"Upon
request\" availability is not acceptable (but online restricted access
only in exceptional cases is) and it is up to the authors to ensure that
proper permission is granted by participants (if the study includes data
obtained in this manner). Materials as intended here include, but are
not limited to, original audio or video recordings, transcripts,
experimental code, stimuli, gathered data files, researchers' notebooks,
derived data, annotations, statistical code etc.

## Discussion

The discussion section, to be added at Stage 2, will include the
author's interpretation of the findings reported in the previous
section, in light of the research topic, questions and/or hypothesis
presented in the Introduction. We recommend to keep the discussion
section short and to the point, while ensuring that due weight is given
to the evidentiary level of the research findings (i.e. any claim made
in this section should be of a magnitude that does not exceed the
magnitude of evidence and uncertainty that characterise the findings).
Suggested further subsections include "Limitations" and "Future
work/Open questions".

## Conclusion

The Conclusion section should briefly summarise the research topic,
questions and/or hypotheses and highlight the main findings in light of
existing gaps. We recommend to write a conclusion that could be read as
stand-alone. It is acceptable for the conclusion to mirror the structure
of the abstract and be an edited and slightly extended version of the
abstract.

## CRediT roles {#credit-roles .unnumbered}

This section must include a list of all authors with Contributor Role
Taxonomy (CRediT) roles listed for each author. See
<https://credit.niso.org>. All authors in the paper must either have a
"Writing -- original draft" role or a "Writing -- review & editing" and
all authors must have at least two roles.

## Acknowledgements {#acknowledgements .unnumbered}

You can use this section to acknowledge feedback and support by external
individuals or institutions.

## Open Research statement {#open-research-statement .unnumbered}

You are required to publicly share the Research Compendium of the study,
which must include all materials like data, code, stimuli,
questionnaires, figures etc. All analyses must be computationally
reproducible (when applicable) or documented to the highest detail and
level of transparency. This section must contain at least the following
statement, where XXX is a link, a DOI, or a (data) citation:

> The Research Compendium of the study is available at XXX.

With a data citation.

> The Research Compendium of the study is available as @coretta2025.

## Conflict of interest {#conflict-of-interest .unnumbered}

You should report here any conflict of interest. If you have no conflict
of interest, write: The authors confirm that there are no conflicts of
interest.

## References {.unnumbered}

